### ISSUE TITLE
Incorrect PCL lib folder in .nuspec file

### ISSUE THREAD

**Issue by anders9ustafsson** [mbrit/MetroLog#69]
In [lines 50-51](https://github.com/mbrit/MetroLog/blob/master/MetroLog.nuspec#L50) of the *MetroLog.nuspec* file, an incorrect target folder is specified. 

The *MetroLog* PCL library currently targets Profile 259, which would translate to folder _lib\portable-net45+wp8+**win**+wpa81_ (or _**win8**_ or _**netcore45**_). However, in the *.nuspec* file, the following folder is currently specified: _lib\portable-net45+wp8+**win81**+wpa81_. This **win81** specification prevents the *MetroLog* NuGet package to be added to PCL Profile 259 projects, as well as projects compatible with this profile, such as Profile 111.

For maximal applicability, it is highly recommended that the folder specification in the *.nuspec* file is updated.

There is also an associated issue with recent additions to Windows 10 and Visual Studio 2015, see [this](http://stackoverflow.com/q/33146399/650012) StackOverflow question. To prepare for future NuGet package compatibility, it is thus also recommended that *dnxcore50* is added to the folder name, summing up to the full name 

_**lib\portable-net45+wp8+win+wpa81+dnxcore50**_.

**Comment by onovotny** [comment]
Hi,

So Win8 is not in the PCL platform list as there is no matching Win 8 implementation -- it's Win8.1+. If I change the PCL marker to `win`, then you could potentially have people add the PCL but not have a matching platform if they try to add it to a win8 app.

Can you update your PCL to be Win8.1 instead of Win8?

If this is a real blocker, I can reconsider.

**Comment by onovotny** [comment]
As to the second issue around `dnxcore50`, I do have a backlog item to support `dotnet` and UWP, but I have not had the time yet. Simply adding `dnxcore50` to the PCL list is incorrect for two reasons:

1.  DNX projects can target either CoreCLR or the full .NET Framework (that's why there's actually `dnx46` and `dnxcore50`)
2.  The `dnxcore50` version would need a full implementation using the .NET Core libraries. Currently the PCL library is more of a façade/reference assembly.

This is not impossible and it's been on my radar, just needs work.

**Comment by anders9ustafsson** [comment]
Profile 259 (which is the [PCL profile](https://github.com/mbrit/MetroLog/blob/master/MetroLog/MetroLog.csproj#L18) *MetroLog* is using) targets _Windows **8**_, see here:

![pcl-259](https://cloud.githubusercontent.com/assets/6515030/10513009/f052d548-7344-11e5-828e-567ea21bf325.png)

If I try to change the selected *Windows* target to *Windows 8.1* in the *Change Targets* dialog, I will be prompted with *The following will be automatically targeted because they support the same set of portable APIs: Windows 8*.

So even if there is no dedicated *Windows 8* version of *MetroLog*, the PCL folder specification **must still** list *win* or *win8*, otherwise the portable library cannot be applied to PCL profile 259 library projects.

**Comment by anders9ustafsson** [comment]
@onovotny It turns out that the *dnxcore50* issue is only relevant on Visual Studio 2013, which uses NuGet 2.8 something. On Visual Studio 2015 (and NuGet 3.x), *dnxcore50* occurrence in the NuGet PCL folder name is not considered. So in conclusion, ignore my initial *dnxcore50* proposal for the time being.

*But*, the **win81** specification still prevents the PCL *MetroLog* package from being added to PCL Profile 259 and 111 projects even in Visual Studio 2015. So, it is absolutely necessary to change the portable folder specification to use **win** instead, regardless of Visual Studio version.

**Comment by onovotny** [comment]
This should be fixed in 0.9.0

**Comment by anders9ustafsson** [comment]
@onovotny Terrific! Many thanks for fixing this. And great work on the library!
